theme: noesya-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  ecosystem: lab
  posts:
    index:
      layout: list
      options:
        image: false
        summary: false